-- seed_materiales.sql
-- Catálogo inicial de materiales extraído de Tabla_DePanas.xlsx
-- Se inserta con OR IGNORE para no duplicar si ya existe

INSERT OR IGNORE INTO materiales_catalogo (nombre, categoria, producto) VALUES
('Agua', 'Bebidas', 'Hidratantes'),
('Ajo Chino', 'Materia Prima', ''),
('Alambrina ExtraFuerte', 'Materia Prima', 'Todos'),
('Anis', 'Materia Prima', 'Golfeados'),
('Azucar', 'Materia Prima', 'Todos'),
('Bandeja Bisagrada', 'Desechables', ''),
('Bandeja Kraft', 'Desechables', ''),
('Bolsa al Vacio 8*12', 'Desechables', 'Tequeños'),
('Cebolla', 'Materia Prima', 'Arepas/Empanadas'),
('Cilantro', 'Materia Prima', 'Salsa'),
('Fosforos', 'Material Común', 'Todos'),
('Frijol Negro', 'Materia Prima', 'Arepas/Empanadas'),
('Gabacha #3 Blanca', 'Desechables', 'Todos'),
('Gatorade', 'Bebidas', 'Hidratantes'),
('Huevos', 'Materia Prima', 'Panadería'),
('Jamon Picnic', 'Materia Prima', 'Cachitos'),
('Jamón de Pavo', 'Materia Prima', 'Cachitos'),
('Lipton', 'Bebidas', 'Gaseosas'),
('Manteca', 'Materia Prima', 'Panadería'),
('Mr Músculo Antigrasa', 'Limpieza', ''),
('Pechugas de Pollo', 'Materia Prima', 'Arepas/Empanadas'),
('Pepsi', 'Bebidas', 'Gaseosas'),
('Perejil', 'Materia Prima', 'Salsa'),
('Pierna Mechada La Rioja', 'Materia Prima', ''),
('Plátanos', 'Materia Prima', 'Arepas/Empanadas'),
('Portion Cup Cuadrada', 'Desechables', ''),
('Sazón Completa', 'Materia Prima', 'Arepas/Empanadas'),
('Tapa Portion Cup Cuadrado', 'Desechables', ''),
('Tapadera Cristal', 'Desechables', ''),
('Tocino La Rioja', 'Materia Prima', 'Cachitos');
